### ISSUE TITLE
[Privacy Manifest] Implementation

### ISSUE THREAD

**Issue by corentios** [DataDome/datadome-ios-package#12]
Hello,

As we approach the upcoming spring and the anticipated implementation of the [Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/) by Apple, it's crucial to ensure that your SDK fully complies with Apple's requirements.

Does your SDK need to include it?
If so, do you have a release date planned?

Thank you in advance for your attention to this matter.

Best regards

**Comment by Kireyin** [comment]
Hello @corentios 

The embedded Privacy Manifest of an SDK is only used to automatically fill APple's privacy questions when you publish your applications. This means that an SDK does not need to include one, even if it would definitely be more convenient for a developer integrating said SDK.

That being said, we do plan to integrate it when our Swift compilator target supports it. Today, we provide support for Xcode 14.1 (as minimum Xcode version supported by APple's AppStoreConnect platform). When we migrate this target to Xcode 15 or newer, we will include the Privacy Manifest into our SDKs.

**Comment by corentios** [comment]
Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to.Describing data use in privacy manifests | Apple Developer Documentationdeveloper.apple.comOn Jan 29, 2024, at 17:41, Kireyin ***@***.***> wrote:﻿
Closed #12 as completed.

**Comment by corentios** [comment]
Hello @Kireyin 

As you can see here : https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

"Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to."

**Comment by mollyIV** [comment]
Hello @Kireyin 👋 

> we do plan to integrate it when our Swift compilator target supports it

That's a good news, thanks for the update.

+1 to @corentios comment. Apple has posted [an update](https://developer.apple.com/news/?id=3d8a9yyh) recently: 

> Starting May 1: ... if you add a new third-party SDK that’s on the list of commonly used third-party SDKs, these API, privacy manifest, and signature requirements will apply to that SDK. Make sure to use a version of the SDK that includes its privacy manifest and note that signatures are also required when the SDK is added as a binary dependency.

The list that Apple mentioned can be found [here](https://developer.apple.com/support/third-party-SDK-requirements/). Even though the `DataDome` is not explicitly mentioned on the list, I am still very much looking forward to adding the Privacy Manifest File to the `DataDome` SDK.

Thanks! 🙇

**Comment by Kireyin** [comment]
All that I can say is that it is planned. 

We are aware that Apple is starting to enforce it for some SDKs and that we could end up on the list any moment. We will of course not wait for Apple to force our hand and we should be able to come back to you on the matter in the near future.

**Comment by mollyIV** [comment]
Thanks! Could we please reopen this issue to maintain visibility on it? 🙏

**Comment by sarodger** [comment]
Is there any update on when this will be delivered please? @Kireyin

**Comment by Kireyin** [comment]
@sarodger - it has been released this morning under version 3.5.0

**Comment by Kireyin** [comment]
@sarodger @mollyIV 
To add some clarification about what has been done:
We included the privacy manifest inside the binary dependency that is embedded inside the Swift Package.
I'll keep this issue open until one of you can confirm that it is enough. If not, just ping me and I will look for a way to have it directly into the Swift Package.

**Comment by mollyIV** [comment]
Thanks a bunch @Kireyin! Can you please also add this version to https://package.datadome.co/ios/DataDomeSDK.json ? 🙏

**Comment by Kireyin** [comment]
It's done @mollyIV - sorry for the delay

**Comment by mollyIV** [comment]
Hi @Kireyin 👋 

It looks like there's a problem with `DataDomeSDK.json` file. We're getting the following error when updating dependency via `Carthage`:

```bash
*** Downloading binary-only framework DataDomeSDK at "https://package.datadome.co/ios/DataDomeSDK.json"
Unable to parse binary-only framework JSON at https://package.datadome.co/ios/DataDomeSDK.json due to error: unable to parse semantic version: expected version in line:
```

Steps to repro: 

1. Add a binary `DataDome` dependency to a `Cartfile`

```
// Cartfile 

binary "https://package.datadome.co/ios/DataDomeSDK.json" == 3.5.0
```

2. Call `carthage update`

```
$ carthage update --platform iOS --cache-builds --no-use-binaries --use-xcframeworks
```

Not sure, but maybe this line in `DataDomeSDK.json` is causing problems
```
"": "https://package.datadome.co/ios/DataDomeSDK-.zip",
```

Can you please have a look at it? 🙏

**Comment by mollyIV** [comment]
Bump ☝️ I am so sorry for the ping, but it's quite an important issue 🙏 @Kireyin

**Comment by Kireyin** [comment]
@mollyIV - sorry for the delayed response, I'm working on it now

**Comment by mollyIV** [comment]
I can confirm it's working fine, thanks!
