### ISSUE TITLE
Package Artefact Can't Be Fetched

### ISSUE THREAD

**Issue by shgew** [DataDome/datadome-ios-package#13]
The artefact linked in the package can't be accessed, because the endpoint returns a 403 error:
> failed downloading 'https://package.datadome.co/ios/DataDomeSDK-3.4.0.zip' which is required by binary target 'DataDomeSDK': badResponseStatusCode(403)

Going to the URL via browser results in the same error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C6CFKDDJ2QQ10XB4</RequestId>
<HostId>o4w5Nof4sQqGE8B7ZkKEaSbA2SAUMUlm1nimW/+OEsKDOCtTvQle1ceaolimrhKbkRXaJVBdP2s=</HostId>
</Error>
```

**Comment by paillou** [comment]
I faced the same issue, which seems to be solved now 👍

**Comment by Kireyin** [comment]
Due to an infrastructure issue, our iOS packages were not available for a few hours this morning.
The issue has now been resolved and all the iOS packages are available again.

We apologise for the inconvenience and we are taking necessary steps to avoid this issue in the future.

**Comment by shgew** [comment]
Thank you, @Kireyin 🙂

**Comment by Kireyin** [comment]
Thank you @shgew for reporting the issue and for you patience!
